Update export.yaml

diff --git a/.github/workflows/export.yaml b/.github/workflows/export.yaml
--- a/.github/workflows/export.yaml
+++ b/.github/workflows/export.yaml
@@ -24,10 +24,16 @@ jobs:
     - name: import project
       run: godot --headless -e --quit-after 100
     - name: Zip up Folder
-      run: ${{vars.ZIPCOMMAND}}
+      run: zip -r build.zip . -x "*.git*" -x "*.github*" -x "*.vscode*" -x ".godot/editor/*" -x "build.zip"
 
     - name: Upload Zip
       run: |
-       curl --data-binary "@build.zip" \
-            "${{secrets.uploadUrl}}?godot_id=${{vars.GODOT_ASSET_ID}}&xogot_id=${{vars.XOGOT_ASSET_ID}}&version=${{ github.ref_name }}&tags=${{vars.TAGS}}&iconUrl=${{vars.ICON_URL}}${{vars.EXTRA_ARGS}}" \
-            -H "apiKey: ${{secrets.apiKey}}"
+        RESPONSE=$(curl --data-binary "@build.zip" \
+            "${{secrets.uploadUrl}}?godot_id=${{env.GODOT_ASSET_ID}}&xodot_id=${{env.XODOT_ASSET_ID}}&version=${{ github.ref_name }}" \
+            -H "apiKey: ${{secrets.apiKey}}")
+        if [ $? -eq 0 ]; then
+          echo "SUCCESS"
+        else
+          echo "FAILURE"
+          exit 1
+        fi
